require "ffi-compiler/compile_task"

FFI::Compiler::CompileTask.new("libxar") do |c|
  c.source_dirs = ['./xar/']

  c.have_header?("stdio.h", "/usr/local/include")
  c.have_func?("puts")
  c.have_library?("z")
end
